name: Codeception

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php-versions: ['5.6', '7.0', '7.1', '7.2', '7.3']

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Show PHP version
      run: php -v
      
    - name: Run test suite
      run: vendor/bin/codecept run
