name: Codeception

on: [push]

jobs:
  build:
    name: PHP ${{matrix.php}}
    
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php: [7.0, 7.1, 7.2, 7.3, nightly]

    steps:
    - uses: actions/checkout@v1

    - name: Setup PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php }}
        extension-csv: mbstring

    - name: Check PHP Version
      run: php -v
      
    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run test suite
      run: vendor/bin/codecept run
